[backend]
admin_api_key = "ADMIN_API_KEY" # Use `uuidgen` to generate a secure password
backend_secret = "BACKEND_SECRET" # Use `uuidgen`

[database]
username = "postgres"
password = "123456" # Use `uuidgen`
host = "localhost"
dbname = "fullstack"

[google_auth]
google_client_id = "GOOGLE_CLIENT_ID"
google_client_secret = "GOOGLE_CLIENT_SECRET"

[email]
email_address = "email"
email_password = "password"
hostname="smtp.gmail.com"
port="587"
